// react-native/src/nav/auth/SignUp.js
import React, { Fragment, Component } from 'react'
import { View, StyleSheet } from 'react-native'

import { Input, ActionButton } from '../../components'
import { Auth } from 'aws-amplify'

class SignIn extends Component {
  state = {
    username: '',
    password: '',
    email: '',
    phone_number: '',
    authCode: '',
    stage: 0
  }
  onChangeText = (key, value) => {
    this.setState({ [key]: value })
  }
  signUp = async () => {
    const {
      username, password, email, phone_number
    } = this.state
    try {
      await Auth.signUp({ username, password, attributes: { email, phone_number }})
      console.log('successful sign up..')
      this.setState({ stage: 1 })
    } catch (err) {
      console.log('error signing up...')
    }
  }
  confirmSignUp = async () => {
    const { username, authCode } = this.state
    try {
      await Auth.confirmSignUp(username, authCode)
      this.props.toggleAuthType()
    } catch (err) {
      console.log('error signing up...', err)
    }
  }
  render() {
    return (
      <View style={styles.container}>
        {
          this.state.stage === Number(0) && (
            <Fragment>
              <Input
                placeholder='Username'
                type='username'
                onChangeText={this.onChangeText}
              />
              <Input
                placeholder='Password'
                type='password'
                onChangeText={this.onChangeText}
                secureTextEntry
              />
              <Input
                placeholder='Email'
                type='email'
                onChangeText={this.onChangeText}
              />
              <Input
                placeholder='Phone Number'
                type='phone_number'
                onChangeText={this.onChangeText}
              />
              <ActionButton
                title='Sign Up'
                onPress={this.signUp}
              />
            </Fragment>
          )
        }
        {
          this.state.stage === Number(1) && (
            <Fragment>
              <Input
                placeholder='Confirmation Code'
                type='authCode'
                onChangeText={this.onChangeText}
              />
              <ActionButton
                title='Confirm Sign Up'
                onPress={this.confirmSignUp}
              />
            </Fragment>
          )
        }
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
  },
  input: {
    backgroundColor: '#fcf3db',
    borderRadius: 30,
    height: 45
  }
})

export default SignIn

// vue/src/components/SignUp.vue
<template>
  <div>
    <div class='form-container'>
      <h1 class='heading'>Sign Up</h1>
      <div class='form' v-if="phase === Number(0)">
        <input
          class='input'
          v-model="form.username"
          placeholder='Username'
        />
        <input
          class='input'
          v-model="form.password"
          placeholder='Password'
          type='password'
        />
        <input
          class='input'
          v-model="form.attributes.email"
          placeholder='Email'
        />
        <input
          class='input'
          v-model="form.attributes.phone_number"
          placeholder='Phone'
        />
        <div class='button' v-on:click="signUp">
          <p>Sign Up</p>
        </div>
      </div>

      <div class='form' v-if="phase === Number(1)">
        <input
          class='input'
          v-model="authCode"
          placeholder='Authentication code'
        />
        <div class='button' v-on:click="confirmSignUp">
          <p>Confirm Sign Up</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>

export default {
  props: ['toggleForm'],
  name: 'sign-up',
  methods: {
    async signUp() {
      try {
        await this.$Amplify.Auth.signUp(this.form)
        this.phase = 1
        console.log('user successfully signed up!')
      } catch (err) {
        console.log('error signing up...')
      }
    },
    async confirmSignUp() {
      try {
        await this.$Amplify.Auth.confirmSignUp(this.form.username, this.authCode)
        this.toggleForm()
        console.log('user successfully signed up!')
      } catch (err) {
        console.log('error signing up...', err)
      }
    }
  },
  data() {
    return {
      form: {
        username: '',
        password: '',
        attributes: {
          email: '',
          phone_number: '',
        }
      },
      authCode: '',
      phase: 0
    }
  }
}
</script>

<style scoped>
.heading {
  text-align: left;
  margin: 55px 5px 15px;
}
.form-container {
  width: 262px;;
  margin: 0 auto;
}
.form {
  display: flex;
  flex-direction: column;
  align-items: center;
}
.button {
  padding: 13px 35px;
  background-color: #2c3e50;
  cursor: pointer;
  box-shadow: 1px 1px 5px rgba(0, 0, 0, .5);
  margin: 25px 0px 20px;
  align-self: flex-start;
}
.button:hover {
  opacity: .9;
}
.button p {
  margin: 0;
  color: white;
  font-weight: 600;
}
</style>
